export 'package:componentes/presentation/screens/progress_indicator_screen.dart';
export 'package:componentes/presentation/screens/animaciones_screen.dart';
export 'package:componentes/presentation/screens/sliders_screen.dart';
export 'package:componentes/presentation/screens/alerta_screen.dart';
export 'package:componentes/presentation/screens/botones_screen.dart';
export 'package:componentes/presentation/screens/home_screen.dart';
export 'package:componentes/presentation/screens/listas_screen.dart';
export 'package:componentes/presentation/screens/tarjestas_screen.dart';
export 'package:componentes/presentation/screens/formulario_screen.dart';