// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjJb1akBXL7a6wp1O-w5IWfyT5lTEsgsg',
    appId: '1:495843096513:android:c72b2e914e044bb0c32140',
    messagingSenderId: '495843096513',
    projectId: 'fireflutterdam-8de7a',
    storageBucket: 'fireflutterdam-8de7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDkwENSQl9lIWUkHJjJy0S22kb7MF8woI',
    appId: '1:495843096513:ios:20a1990c0b8d2ee1c32140',
    messagingSenderId: '495843096513',
    projectId: 'fireflutterdam-8de7a',
    storageBucket: 'fireflutterdam-8de7a.firebasestorage.app',
    androidClientId: '495843096513-251d8rhmbsvunrk4hr40gtkqoinkjm8c.apps.googleusercontent.com',
    iosClientId: '495843096513-172v6b8gm6uuj144r2rvmdjkk7fike7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
