// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGf0KAxkcn0FqtZ6y-dwV5rBpA8RCwWEk',
    appId: '1:385386356311:android:9622e9fe7702d753404d12',
    messagingSenderId: '385386356311',
    projectId: 'fir-dam2-ef6f0',
    storageBucket: 'fir-dam2-ef6f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7pANYFeTwBmFYo8UwK07KfS4jRrLQNmc',
    appId: '1:385386356311:ios:f72231d2fa4ef4ba404d12',
    messagingSenderId: '385386356311',
    projectId: 'fir-dam2-ef6f0',
    storageBucket: 'fir-dam2-ef6f0.firebasestorage.app',
    androidClientId: '385386356311-3ona9c0n42eskjhtgc930p2llj5ko2g2.apps.googleusercontent.com',
    iosClientId: '385386356311-go6d2l9c49esqs14asis02t97isf3eu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
