// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Ncj75XR3jB5vPR6c3P2isS5ATN8JTcs',
    appId: '1:495843096513:web:363c783fa92061cdc32140',
    messagingSenderId: '495843096513',
    projectId: 'fireflutterdam-8de7a',
    authDomain: 'fireflutterdam-8de7a.firebaseapp.com',
    storageBucket: 'fireflutterdam-8de7a.firebasestorage.app',
    measurementId: 'G-DBSDEQTFK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjJb1akBXL7a6wp1O-w5IWfyT5lTEsgsg',
    appId: '1:495843096513:android:c72b2e914e044bb0c32140',
    messagingSenderId: '495843096513',
    projectId: 'fireflutterdam-8de7a',
    storageBucket: 'fireflutterdam-8de7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDkwENSQl9lIWUkHJjJy0S22kb7MF8woI',
    appId: '1:495843096513:ios:20a1990c0b8d2ee1c32140',
    messagingSenderId: '495843096513',
    projectId: 'fireflutterdam-8de7a',
    storageBucket: 'fireflutterdam-8de7a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDkwENSQl9lIWUkHJjJy0S22kb7MF8woI',
    appId: '1:495843096513:ios:20a1990c0b8d2ee1c32140',
    messagingSenderId: '495843096513',
    projectId: 'fireflutterdam-8de7a',
    storageBucket: 'fireflutterdam-8de7a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Ncj75XR3jB5vPR6c3P2isS5ATN8JTcs',
    appId: '1:495843096513:web:0d3bffeb783b4b8dc32140',
    messagingSenderId: '495843096513',
    projectId: 'fireflutterdam-8de7a',
    authDomain: 'fireflutterdam-8de7a.firebaseapp.com',
    storageBucket: 'fireflutterdam-8de7a.firebasestorage.app',
    measurementId: 'G-GFWEMNFL09',
  );
}
