-- MySQL Script generated by MySQL Workbench
-- Tue Nov 11 14:45:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`instalacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`instalacion` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`instalacion` (
  `IDInstalacion` INT NOT NULL,
  `Tipo` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `FechaUltimoMantenimiento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IDInstalacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`material_deportivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`material_deportivo` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`material_deportivo` (
  `IDMaterial` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`IDMaterial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`socio` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`socio` (
  `DNI` VARCHAR(9) NOT NULL,
  `Contraseña` VARCHAR(64) NOT NULL,
  `NombreCompleto` VARCHAR(100) NOT NULL,
  `Dirección` VARCHAR(150) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `CuentaBancaria` VARCHAR(34) NULL DEFAULT NULL,
  PRIMARY KEY (`DNI`),
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`reserva` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`reserva` (
  `IdReserva` INT NOT NULL,
  `NumeroParticipantes` INT NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `FechaHoraInicio` DATETIME NOT NULL,
  `FechaHoraFin` DATETIME NOT NULL,
  `DNI` VARCHAR(9) NOT NULL,
  `IDInstalacion` INT NOT NULL,
  PRIMARY KEY (`IdReserva`),
  INDEX `DNI` (`DNI` ASC) VISIBLE,
  INDEX `IDInstalacion` (`IDInstalacion` ASC) VISIBLE,
  CONSTRAINT `reserva_ibfk_1`
    FOREIGN KEY (`DNI`)
    REFERENCES `proyecto`.`socio` (`DNI`),
  CONSTRAINT `reserva_ibfk_2`
    FOREIGN KEY (`IDInstalacion`)
    REFERENCES `proyecto`.`instalacion` (`IDInstalacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`material_reservado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`material_reservado` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`material_reservado` (
  `IdReserva` INT NOT NULL,
  `IDMaterial` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Observaciones` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`IdReserva`, `IDMaterial`),
  INDEX `IDMaterial` (`IDMaterial` ASC) VISIBLE,
  CONSTRAINT `material_reservado_ibfk_1`
    FOREIGN KEY (`IdReserva`)
    REFERENCES `proyecto`.`reserva` (`IdReserva`),
  CONSTRAINT `material_reservado_ibfk_2`
    FOREIGN KEY (`IDMaterial`)
    REFERENCES `proyecto`.`material_deportivo` (`IDMaterial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`pago` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`pago` (
  `ReferenciaPago` VARCHAR(20) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Concepto` VARCHAR(100) NULL DEFAULT NULL,
  `MetodoPago` VARCHAR(30) NULL DEFAULT NULL,
  `DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ReferenciaPago`),
  INDEX `DNI` (`DNI` ASC) VISIBLE,
  CONSTRAINT `pago_ibfk_1`
    FOREIGN KEY (`DNI`)
    REFERENCES `proyecto`.`socio` (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`Administrador` (
  `ID` INT NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
