// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIufYT7VF8zndCR09dbC_oKqGYl28_vr8',
    appId: '1:897793124837:web:eb37ca06a9c602a94d670c',
    messagingSenderId: '897793124837',
    projectId: 'repasoexamen-6e211',
    authDomain: 'repasoexamen-6e211.firebaseapp.com',
    storageBucket: 'repasoexamen-6e211.firebasestorage.app',
    measurementId: 'G-ZHDNVSKD2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDkJPKHT4rSTiihw_BDAZmv6ws-ps5QX8',
    appId: '1:897793124837:android:a965165c01f08e574d670c',
    messagingSenderId: '897793124837',
    projectId: 'repasoexamen-6e211',
    storageBucket: 'repasoexamen-6e211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB-kzK8lVpjH3atguv-bwAbgx_8rkn-EA',
    appId: '1:897793124837:ios:b0b8dfedd0dc40a64d670c',
    messagingSenderId: '897793124837',
    projectId: 'repasoexamen-6e211',
    storageBucket: 'repasoexamen-6e211.firebasestorage.app',
    iosBundleId: 'com.example.repasoDavid',
  );
}
